[package]
name = "webasmtest"
version = "0.1.0"
authors = ["Enrique <niofis@gmail.com>"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
rand="0.3.14"
